/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/odo/auth/authz/permission/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_permission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/permission/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_permission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/permission/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["list_permissions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/permission/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_permission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/role-permission/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_role_permission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/role-permission/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_role_permission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/role-permission/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_role_permission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/role/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_role"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/role/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_role"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/role/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["get_role"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/role/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["list_roles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/role/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_role"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/user-has-perm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user_has_perm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/user-has-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user_has_role"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/user-perm-scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user_perm_scopes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/user-role/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_assignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/user-role/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_assignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/user-role/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["list_assignments"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/user-roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user_roles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/authz/users-with-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["users_with_role"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/saml/admin/attr-role-map/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_attr_role_map"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/saml/admin/attr-role-map/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_attr_role_map"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/saml/admin/attr-role-map/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["list_attr_role_maps"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/saml/admin/attr-role-map/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_attr_role_map"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/saml/admin/attribute/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_attribute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/saml/admin/attribute/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_attribute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/saml/admin/attribute/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["list_attributes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/saml/admin/attribute/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_attribute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/saml/admin/idp/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_idp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/saml/admin/idp/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_idp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/saml/admin/idp/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["list_idps"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/saml/admin/idp/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_idp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/saml/admin/sp/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_sp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/saml/admin/sp/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_sp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/saml/admin/sp/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["list_sps"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/saml/admin/sp/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_sp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/token/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revoke_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/token/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validate_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/user/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a user account (and optionally its local-account password).
         * @description This is the API face of what create-local-account.sh used to do with
         *     direct SQL: app registration and test fixtures provision their users
         *     here, then assign roles via authz/user-role/create.
         */
        post: operations["create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/user/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user_detail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/user/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["get_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/user/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user_search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/auth/user/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssignmentIdRequest: {
            /** Format: int32 */
            id: number;
        };
        AssignmentRow: {
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            id: number;
            is_managed_by_saml: boolean;
            /** Format: int32 */
            org_unit: number;
            org_unit_label: string;
            role: string;
            role_label: string;
            /** Format: int32 */
            usr: number;
        };
        AssignmentSuccessResponse: {
            success: boolean;
        };
        AttrRoleMapIdRequest: {
            /** Format: int32 */
            id: number;
        };
        /** @description One page of SAML attribute-to-role mappings. */
        AttrRoleMapPage: {
            /** @description The rows on this page. */
            rows: components["schemas"]["AttrRoleMapRow"][];
            /**
             * Format: int64
             * @description Total rows matching the filter, ignoring limit/offset.
             */
            total: number;
        };
        AttrRoleMapRow: {
            /** Format: int32 */
            attr: number;
            attr_key: string;
            attr_value: string;
            /** Format: int32 */
            id: number;
            idp_name: string;
            is_active: boolean;
            role: string;
            role_label: string;
        };
        AttributeIdRequest: {
            /** Format: int32 */
            id: number;
        };
        AttributeRow: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            idp: number;
            idp_name: string;
            is_location: boolean;
            key: string;
            label: string;
            /**
             * Format: int64
             * @description Role mappings referencing this attribute.
             */
            mapping_count: number;
            normalizer?: string | null;
        };
        AuthzAdminSuccessResponse: {
            success: boolean;
        };
        AuthzPermResponse: {
            has_perm: boolean;
            /** Format: int32 */
            org_unit?: number | null;
            perm: string;
            /** Format: int32 */
            user_id: number;
        };
        AuthzRoleResponse: {
            has_role: boolean;
            /** Format: int32 */
            org_unit?: number | null;
            role: string;
            /** Format: int32 */
            user_id: number;
        };
        CreateAssignmentRequest: {
            /** Format: int32 */
            org_unit?: number | null;
            /** @description Org unit by stable uuid (accepted alongside `org_unit`; id wins). */
            org_unit_uuid?: string | null;
            role: string;
            /** Format: int32 */
            usr?: number | null;
            /** @description User by stable uuid (accepted alongside `usr`; id wins). */
            usr_uuid?: string | null;
        };
        CreateAttrRoleMapRequest: {
            /** Format: int32 */
            attr: number;
            attr_value: string;
            is_active?: boolean | null;
            role: string;
        };
        CreateAttributeRequest: {
            /** Format: int32 */
            idp: number;
            is_location?: boolean | null;
            key: string;
            label: string;
            normalizer?: string | null;
        };
        CreateIdpRequest: {
            allow_idp_initiated?: boolean | null;
            attribute_mapping?: unknown;
            entity_id: string;
            is_active?: boolean | null;
            metadata_url?: string | null;
            name: string;
            /** Format: int32 */
            session_lifetime_hours?: number | null;
            slo_url?: string | null;
            sso_url?: string | null;
        };
        CreatePermissionRequest: {
            code: string;
            description?: string | null;
        };
        CreateRolePermissionRequest: {
            /** Format: int32 */
            min_depth?: number;
            perm: string;
            role: string;
        };
        CreateRoleRequest: {
            code: string;
            description?: string | null;
            label: string;
        };
        CreateSpRequest: {
            acs_url: string;
            callback_url?: string | null;
            entity_id: string;
            /** Format: int32 */
            idp?: number | null;
            idp_x509_cert?: string | null;
            is_active?: boolean | null;
            label?: string | null;
            metadata_url?: string | null;
            private_key: string;
            slo_url?: string | null;
            x509_cert: string;
        };
        CreateUserRequest: {
            /**
             * @description "local" (default) or "saml". SAML accounts are normally created at
             *     first SSO login; creating one here pre-provisions it.
             */
            auth_method?: string | null;
            email: string;
            family_name?: string | null;
            first_given_name?: string | null;
            /**
             * @description Sets the local-account password. Local accounts without a password
             *     cannot log in until one is set. Rejected for SAML accounts.
             */
            password?: string | null;
            second_given_name?: string | null;
            username: string;
            /**
             * @description Pin the stable uuid (durable references; fixtures and app
             *     registration pin well-known uuids). Random when omitted.
             */
            uuid?: string | null;
        };
        GetUserOptions: {
            /**
             * @description Opt in to resolve a soft-deleted user (flagged with deleted_at) instead
             *     of 404. Default false keeps get_user active-only.
             */
            with_deleted?: boolean;
            with_working_locations?: boolean;
        };
        GetUserRequest: {
            /** Format: int32 */
            id?: number | null;
            options?: null | components["schemas"]["GetUserOptions"];
            /** @description Resolve by stable uuid instead of database id (durable references). */
            uuid?: string | null;
        };
        GrantRow: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            min_depth: number;
            perm: string;
            perm_description?: string | null;
        };
        IdpIdRequest: {
            /** Format: int32 */
            id: number;
        };
        IdpRow: {
            allow_idp_initiated: boolean;
            attribute_mapping?: unknown;
            /** Format: date-time */
            created_at?: string | null;
            entity_id: string;
            /** Format: int32 */
            id: number;
            is_active: boolean;
            metadata_url?: string | null;
            name: string;
            /** Format: int32 */
            session_lifetime_hours?: number | null;
            slo_url?: string | null;
            /**
             * Format: int64
             * @description Service providers configured against this IdP.
             */
            sp_count: number;
            sso_url?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
            /**
             * Format: int64
             * @description Users with a SAML identity from this IdP.
             */
            user_count: number;
        };
        ListAssignmentsRequest: {
            /** Format: int32 */
            usr?: number | null;
            /** @description User by stable uuid (accepted alongside `usr`; id wins). */
            usr_uuid?: string | null;
        };
        ListAssignmentsResponse: {
            assignments: components["schemas"]["AssignmentRow"][];
        };
        ListAttrRoleMapsRequest: components["schemas"]["Page"] & components["schemas"]["Sort"] & {
            /**
             * Format: int32
             * @description Restrict to a single attribute.
             */
            attr?: number | null;
            /**
             * Format: int32
             * @description Restrict to mappings whose attribute belongs to this IdP.
             */
            idp?: number | null;
            /** @description Restrict to a single role code. */
            role?: string | null;
            /** @description Case-insensitive substring match on the attribute value. */
            search?: string | null;
        };
        ListAttributesResponse: {
            attributes: components["schemas"]["AttributeRow"][];
        };
        ListIdpsResponse: {
            idps: components["schemas"]["IdpRow"][];
        };
        ListPermissionsRequest: components["schemas"]["Page"] & components["schemas"]["Sort"] & {
            search?: string | null;
        };
        ListRolesRequest: components["schemas"]["Page"] & components["schemas"]["Sort"] & {
            search?: string | null;
        };
        ListSpsResponse: {
            sps: components["schemas"]["SpRow"][];
        };
        LocalAccountRow: {
            /** Format: date-time */
            created_at?: string | null;
            /** Format: int32 */
            failed_login_attempts: number;
            /** Format: date-time */
            locked_until?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        LoginRequest: {
            ip_address?: string | null;
            /**
             * @description Working org unit by stable uuid (uuid migration 1d.3: the
             *     login/session surface no longer accepts integer org ids; the
             *     `org_unit_uuid` name is kept as an alias for older clients).
             */
            org_unit?: string | null;
            password: string;
            user_agent?: string | null;
            username: string;
        };
        LoginResponse: {
            access_token: string;
            /** Format: int64 */
            expires_in: number;
            /** Format: int64 */
            refresh_expires_at: number;
            token_type: string;
            user: components["schemas"]["UserInfo"];
        };
        LogoutRequest: {
            access_token?: string | null;
            revoke_all_sessions?: boolean;
        };
        LogoutResponse: {
            message: string;
            success: boolean;
        };
        /**
         * @description Standard pagination inputs for admin list endpoints. Flatten this into a
         *     per-resource request struct alongside that resource's own filter fields:
         *
         *     ```ignore
         *     #[derive(Deserialize, ToSchema)]
         *     pub struct ListThingsRequest {
         *         #[serde(default)]
         *         search: Option<String>,
         *         #[serde(flatten)]
         *         page: Page,
         *     }
         *     ```
         */
        Page: {
            /** Format: int64 */
            limit?: number | null;
            /** Format: int64 */
            offset?: number | null;
        };
        /** @description A permission the user effectively holds, plus where it applies. */
        PermScopeRow: {
            description?: string | null;
            /**
             * @description True when the permission applies at every org unit (covers the root);
             *     `scope_units` is then empty.
             */
            global: boolean;
            perm: string;
            /**
             * @description Minimal set of subtree roots the permission applies within. Empty when
             *     `global` is true.
             */
            scope_units: components["schemas"]["ScopeUnit"][];
        };
        PermissionCodeRequest: {
            code: string;
        };
        /** @description One page of permissions. */
        PermissionPage: {
            /** @description The rows on this page. */
            rows: components["schemas"]["PermissionRow"][];
            /**
             * Format: int64
             * @description Total rows matching the filter, ignoring limit/offset.
             */
            total: number;
        };
        PermissionRow: {
            code: string;
            description?: string | null;
            /**
             * Format: int64
             * @description Number of roles this permission is granted to.
             */
            role_count: number;
        };
        RefreshRequest: {
            /**
             * @description Working org unit by stable uuid (uuid migration 1d.3: the
             *     login/session surface no longer accepts integer org ids; the
             *     `org_unit_uuid` name is kept as an alias for older clients).
             */
            org_unit?: string | null;
            refresh_token?: string | null;
        };
        RefreshResponse: {
            access_token: string;
            /** Format: int64 */
            expires_in: number;
            /** Format: int64 */
            refresh_expires_at: number;
            token_type: string;
        };
        RevokeRequest: {
            token: string;
            token_type?: string;
        };
        RevokeResponse: {
            message: string;
            success: boolean;
        };
        RoleAssignment: {
            /** Format: int32 */
            org_unit: number;
            role: string;
        };
        RoleCodeRequest: {
            code: string;
        };
        RoleDetailResponse: {
            grants: components["schemas"]["GrantRow"][];
            role: components["schemas"]["RoleRow"];
        };
        /** @description One page of roles. */
        RolePage: {
            /** @description The rows on this page. */
            rows: components["schemas"]["RoleRow"][];
            /**
             * Format: int64
             * @description Total rows matching the filter, ignoring limit/offset.
             */
            total: number;
        };
        RolePermissionIdRequest: {
            /** Format: int32 */
            id: number;
        };
        RolePermissionRow: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            min_depth: number;
            perm: string;
            role: string;
        };
        RoleRow: {
            code: string;
            description?: string | null;
            label: string;
            /**
             * Format: int64
             * @description Number of permissions granted to this role.
             */
            perm_count: number;
            /**
             * Format: int64
             * @description Number of distinct users holding this role at any org unit.
             */
            user_count: number;
        };
        SamlAdminSuccessResponse: {
            success: boolean;
        };
        SamlAttrSuccessResponse: {
            success: boolean;
        };
        SamlIdentityRow: {
            /** Format: date-time */
            created_at?: string | null;
            /** Format: int32 */
            idp: number;
            idp_name: string;
            name_id: string;
            name_id_format?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        SamlUserAttrRow: {
            key: string;
            label: string;
            value: string;
        };
        /** @description One org-unit subtree root where a permission applies ("<label> and below"). */
        ScopeUnit: {
            /** Format: int32 */
            id: number;
            label: string;
        };
        SessionRow: {
            auth_method: string;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            expires_at: string;
            ip_address?: string | null;
            is_active: boolean;
            /** Format: date-time */
            last_activity_at?: string | null;
            /** Format: int32 */
            org_unit?: number | null;
            org_unit_label?: string | null;
            user_agent?: string | null;
        };
        /**
         * @description Standard sort inputs for admin list endpoints. Flatten this into a
         *     per-resource request struct alongside `Page`:
         *
         *     ```ignore
         *     #[derive(Deserialize, ToSchema)]
         *     pub struct ListThingsRequest {
         *         #[serde(default)]
         *         search: Option<String>,
         *         #[serde(flatten)]
         *         page: Page,
         *         #[serde(flatten)]
         *         sort: Sort,
         *     }
         *     ```
         *
         *     `sort_by` is a client-supplied string, so a handler must NEVER map it to a
         *     column directly — resolve it against an explicit allow-list with
         *     [`Sort::resolve`], which falls back to the handler's default for any
         *     unknown or absent key.
         */
        Sort: {
            /** @description Logical column key to sort by (must be one the handler allow-lists). */
            sort_by?: string | null;
            sort_dir?: null | components["schemas"]["SortDir"];
        };
        /**
         * @description Sort direction for a list endpoint.
         * @enum {string}
         */
        SortDir: "asc" | "desc";
        SpIdRequest: {
            /** Format: int32 */
            id: number;
        };
        /** @description SP row for API responses. Never carries the private key. */
        SpRow: {
            acs_url: string;
            callback_url?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            entity_id: string;
            has_private_key: boolean;
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            idp?: number | null;
            idp_name?: string | null;
            idp_x509_cert?: string | null;
            is_active: boolean;
            label?: string | null;
            metadata_url?: string | null;
            slo_url?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
            x509_cert: string;
        };
        TokenClaims: {
            auth_method: string;
            display_name?: string | null;
            email: string;
            /** Format: int64 */
            expires_at: number;
            /** Format: int64 */
            issued_at: number;
            session_id: string;
            /** Format: int64 */
            user_id: number;
        };
        UpdateAttrRoleMapRequest: {
            /** Format: int32 */
            attr?: number | null;
            attr_value?: string | null;
            /** Format: int32 */
            id: number;
            is_active?: boolean | null;
            role?: string | null;
        };
        UpdateAttributeRequest: {
            /** Format: int32 */
            id: number;
            is_location?: boolean | null;
            key?: string | null;
            label?: string | null;
            /** @description Empty string clears the normalizer. */
            normalizer?: string | null;
        };
        UpdateIdpRequest: {
            allow_idp_initiated?: boolean | null;
            attribute_mapping?: unknown;
            entity_id?: string | null;
            /** Format: int32 */
            id: number;
            is_active?: boolean | null;
            metadata_url?: string | null;
            name?: string | null;
            /** Format: int32 */
            session_lifetime_hours?: number | null;
            slo_url?: string | null;
            sso_url?: string | null;
        };
        UpdatePermissionRequest: {
            code: string;
            description?: string | null;
        };
        UpdateRolePermissionRequest: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            min_depth: number;
        };
        UpdateRoleRequest: {
            code: string;
            description?: string | null;
            label?: string | null;
        };
        UpdateSpRequest: {
            acs_url?: string | null;
            callback_url?: string | null;
            entity_id?: string | null;
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            idp?: number | null;
            idp_x509_cert?: string | null;
            is_active?: boolean | null;
            label?: string | null;
            metadata_url?: string | null;
            /** @description Empty or absent leaves the existing key unchanged. */
            private_key?: string | null;
            slo_url?: string | null;
            x509_cert?: string | null;
        };
        UpdateUserRequest: {
            /**
             * @description Soft-delete action: `true` marks the account deleted (server stamps
             *     deleted_at/deleted_by), `false` restores it. Omitted leaves it as-is.
             */
            deleted?: boolean | null;
            family_name?: string | null;
            /** @description Empty string clears the field. */
            first_given_name?: string | null;
            /** Format: int32 */
            id: number;
            second_given_name?: string | null;
        };
        UserAccountRow: {
            auth_method: string;
            /** Format: date-time */
            created_at?: string | null;
            /**
             * Format: date-time
             * @description Soft-delete timestamp; null when the account is active. odo never
             *     hard-deletes shared rows, so a deleted account stays resolvable.
             */
            deleted_at?: string | null;
            /**
             * Format: int32
             * @description Id of the user who soft-deleted this account (if deleted).
             */
            deleted_by?: number | null;
            display_name: string;
            email: string;
            family_name?: string | null;
            first_given_name?: string | null;
            /** Format: int32 */
            id: number;
            /** Format: date-time */
            last_login_at?: string | null;
            status?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
            username?: string | null;
        };
        UserDetailRequest: {
            /** Format: int32 */
            id: number;
        };
        UserDetailResponse: {
            local_account?: null | components["schemas"]["LocalAccountRow"];
            roles: components["schemas"]["AssignmentRow"][];
            saml_attributes: components["schemas"]["SamlUserAttrRow"][];
            saml_identities: components["schemas"]["SamlIdentityRow"][];
            /** @description Most recent sessions, newest first. */
            sessions: components["schemas"]["SessionRow"][];
            user: components["schemas"]["UserAccountRow"];
        };
        UserHasPermRequest: {
            /** Format: int32 */
            org_unit?: number | null;
            /** @description Org unit by stable uuid (accepted alongside `org_unit`; id wins). */
            org_unit_uuid?: string | null;
            perm: string;
        };
        UserHasRoleRequest: {
            /** Format: int32 */
            org_unit?: number | null;
            /** @description Org unit by stable uuid (accepted alongside `org_unit`; id wins). */
            org_unit_uuid?: string | null;
            role: string;
        };
        UserInfo: {
            display_name: string;
            email: string;
            /** Format: int32 */
            id: number;
            username: string;
        };
        UserPermScopesResponse: {
            perms: components["schemas"]["PermScopeRow"][];
        };
        UserResponse: {
            /**
             * @description RFC3339 soft-delete timestamp; null for active users. get_user resolves
             *     by id and returns soft-deleted users flagged so historical `*_by`
             *     references still render (login/search stay active-only).
             */
            deleted_at?: string | null;
            display_name: string;
            email: string;
            family_name?: string | null;
            first_given_name?: string | null;
            /** Format: int32 */
            id: number;
            second_given_name?: string | null;
            status?: string | null;
            username?: string | null;
            /** @description Stable, DB-independent identity (see odo-durable-references). */
            uuid: string;
            /**
             * @description Stable uuids of the working org units, parallel to
             *     `working_org_units` (uuid migration).
             */
            working_org_unit_uuids?: string[] | null;
            working_org_units?: number[] | null;
        };
        UserRolesResponse: {
            roles: components["schemas"]["RoleAssignment"][];
            /** Format: int32 */
            user_id: number;
        };
        UserSearchRequest: {
            keywords?: string | null;
            /** Format: int64 */
            limit?: number | null;
            /** Format: int64 */
            offset?: number | null;
            options?: null | components["schemas"]["GetUserOptions"];
            status?: string | null;
        };
        UsersWithRoleRequest: {
            /** Format: int32 */
            org_unit?: number | null;
            /** @description Org unit by stable uuid (accepted alongside `org_unit`; id wins). */
            org_unit_uuid?: string | null;
            role: string;
            user_ids?: number[];
            /** @description Users by stable uuid (accepted alongside `user_ids`). */
            user_uuids?: string[];
        };
        UsersWithRoleResponse: {
            /** Format: int32 */
            org_unit?: number | null;
            role: string;
            /** @description Subset of the requested user_ids who hold the role. */
            user_ids: number[];
            /** @description Uuids of the holders (covers users requested by uuid too). */
            user_uuids: string[];
        };
        ValidateRequest: {
            token: string;
        };
        ValidateTokenResponse: {
            claims?: null | components["schemas"]["TokenClaims"];
            error: string;
            valid: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_permission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePermissionRequest"];
            };
        };
        responses: {
            /** @description Newly-created permission */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionRow"];
                };
            };
        };
    };
    delete_permission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermissionCodeRequest"];
            };
        };
        responses: {
            /** @description Permission deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthzAdminSuccessResponse"];
                };
            };
        };
    };
    list_permissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListPermissionsRequest"];
            };
        };
        responses: {
            /** @description Permissions with grant counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionPage"];
                };
            };
        };
    };
    update_permission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePermissionRequest"];
            };
        };
        responses: {
            /** @description Updated permission */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionRow"];
                };
            };
        };
    };
    create_role_permission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRolePermissionRequest"];
            };
        };
        responses: {
            /** @description Newly-created permission grant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolePermissionRow"];
                };
            };
        };
    };
    delete_role_permission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolePermissionIdRequest"];
            };
        };
        responses: {
            /** @description Permission grant revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthzAdminSuccessResponse"];
                };
            };
        };
    };
    update_role_permission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRolePermissionRequest"];
            };
        };
        responses: {
            /** @description Updated permission grant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolePermissionRow"];
                };
            };
        };
    };
    create_role: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleRequest"];
            };
        };
        responses: {
            /** @description Newly-created role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleRow"];
                };
            };
        };
    };
    delete_role: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCodeRequest"];
            };
        };
        responses: {
            /** @description Role deleted along with its permission grants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthzAdminSuccessResponse"];
                };
            };
        };
    };
    get_role: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCodeRequest"];
            };
        };
        responses: {
            /** @description Role with its permission grants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDetailResponse"];
                };
            };
        };
    };
    list_roles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListRolesRequest"];
            };
        };
        responses: {
            /** @description Roles with grant and user counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolePage"];
                };
            };
        };
    };
    update_role: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description Updated role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleRow"];
                };
            };
        };
    };
    user_has_perm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserHasPermRequest"];
            };
        };
        responses: {
            /** @description Permission check result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthzPermResponse"];
                };
            };
        };
    };
    user_has_role: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserHasRoleRequest"];
            };
        };
        responses: {
            /** @description Role check result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthzRoleResponse"];
                };
            };
        };
    };
    user_perm_scopes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListAssignmentsRequest"];
            };
        };
        responses: {
            /** @description A user's effective permissions and where each applies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPermScopesResponse"];
                };
            };
        };
    };
    create_assignment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssignmentRequest"];
            };
        };
        responses: {
            /** @description Newly-created role assignment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentRow"];
                };
            };
        };
    };
    delete_assignment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentIdRequest"];
            };
        };
        responses: {
            /** @description Role assignment removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentSuccessResponse"];
                };
            };
        };
    };
    list_assignments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListAssignmentsRequest"];
            };
        };
        responses: {
            /** @description A user's role assignments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAssignmentsResponse"];
                };
            };
        };
    };
    user_roles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User's role assignments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRolesResponse"];
                };
            };
        };
    };
    users_with_role: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsersWithRoleRequest"];
            };
        };
        responses: {
            /** @description Subset of user_ids that hold the role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsersWithRoleResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Logout processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    create_attr_role_map: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAttrRoleMapRequest"];
            };
        };
        responses: {
            /** @description Newly-created attribute role mapping */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttrRoleMapRow"];
                };
            };
        };
    };
    delete_attr_role_map: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttrRoleMapIdRequest"];
            };
        };
        responses: {
            /** @description Attribute role mapping deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlAttrSuccessResponse"];
                };
            };
        };
    };
    list_attr_role_maps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListAttrRoleMapsRequest"];
            };
        };
        responses: {
            /** @description Filtered SAML attribute-to-role mappings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttrRoleMapPage"];
                };
            };
        };
    };
    update_attr_role_map: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAttrRoleMapRequest"];
            };
        };
        responses: {
            /** @description Updated attribute role mapping */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttrRoleMapRow"];
                };
            };
        };
    };
    create_attribute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAttributeRequest"];
            };
        };
        responses: {
            /** @description Newly-created SAML attribute */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeRow"];
                };
            };
        };
    };
    delete_attribute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttributeIdRequest"];
            };
        };
        responses: {
            /** @description SAML attribute deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlAttrSuccessResponse"];
                };
            };
        };
    };
    list_attributes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All tracked SAML attributes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAttributesResponse"];
                };
            };
        };
    };
    update_attribute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAttributeRequest"];
            };
        };
        responses: {
            /** @description Updated SAML attribute */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeRow"];
                };
            };
        };
    };
    create_idp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIdpRequest"];
            };
        };
        responses: {
            /** @description Newly-created IdP config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdpRow"];
                };
            };
        };
    };
    delete_idp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdpIdRequest"];
            };
        };
        responses: {
            /** @description IdP config deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlAdminSuccessResponse"];
                };
            };
        };
    };
    list_idps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All SAML identity provider configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListIdpsResponse"];
                };
            };
        };
    };
    update_idp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIdpRequest"];
            };
        };
        responses: {
            /** @description Updated IdP config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdpRow"];
                };
            };
        };
    };
    create_sp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpRequest"];
            };
        };
        responses: {
            /** @description Newly-created SP config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpRow"];
                };
            };
        };
    };
    delete_sp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpIdRequest"];
            };
        };
        responses: {
            /** @description SP config deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlAdminSuccessResponse"];
                };
            };
        };
    };
    list_sps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All SAML service provider configs (private keys omitted) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSpsResponse"];
                };
            };
        };
    };
    update_sp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSpRequest"];
            };
        };
        responses: {
            /** @description Updated SP config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpRow"];
                };
            };
        };
    };
    refresh_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Token refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeRequest"];
            };
        };
        responses: {
            /** @description Revocation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeResponse"];
                };
            };
        };
    };
    validate_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateTokenResponse"];
                };
            };
        };
    };
    create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAccountRow"];
                };
            };
        };
    };
    user_detail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserDetailRequest"];
            };
        };
        responses: {
            /** @description Detailed account view for one user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
        };
    };
    get_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetUserRequest"];
            };
        };
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    user_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSearchRequest"];
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    update_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Updated user account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAccountRow"];
                };
            };
        };
    };
}
