/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/odo/org/admin/address/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_address"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/admin/address/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_address"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/admin/address/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_address"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/admin/closure/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_closure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/admin/closure/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_closure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/admin/closure/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_closure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/admin/operating-hours/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_operating_hours"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/admin/operating-hours/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_operating_hours"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/admin/operating-hours/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_operating_hours"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/admin/unit-children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["list_unit_children"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/admin/unit-type/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_unit_type"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/admin/unit-type/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_unit_type"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/admin/unit-type/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["list_unit_types"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/admin/unit-type/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_unit_type"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/admin/unit/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_unit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/admin/unit/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_unit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/admin/unit/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_unit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/root": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["org_unit_root"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["org_unit_tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/unit/label-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch lookup of org-unit `(code, label)` keyed by id.
         * @description Built for callers that hold a set of org_unit ids and just need
         *     display labels — e.g. patron.search's per-page decoration. Unknown ids
         *     are silently dropped from the response.
         */
        post: operations["org_unit_label_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/unit/uuid/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unit detail by stable uuid (durable references): same response and
         *     soft-delete semantics as the id route.
         */
        get: operations["org_unit_detail_by_uuid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/unit/uuid/{uuid}/ancestors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ancestor chain by stable uuid. */
        get: operations["org_unit_ancestors_by_uuid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/unit/uuid/{uuid}/descendants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Descendant subtree by stable uuid. */
        get: operations["org_unit_descendants_by_uuid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/unit/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["org_unit_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/unit/{id}/ancestors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["org_unit_ancestors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/org/unit/{id}/descendants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["org_unit_descendants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddressIdRequest: {
            /** Format: int32 */
            id: number;
        };
        AddressResponse: {
            address_line1?: string | null;
            address_line2?: string | null;
            address_type: string;
            city?: string | null;
            /** Format: int32 */
            id: number;
            label: string;
            /** Format: int32 */
            org_unit: number;
            postal_code?: string | null;
            state_province?: string | null;
        };
        AddressRow: {
            address_line1?: string | null;
            address_line2?: string | null;
            address_type: string;
            city?: string | null;
            /** Format: int32 */
            id: number;
            label: string;
            /** Format: int32 */
            org_unit: number;
            postal_code?: string | null;
            state_province?: string | null;
        };
        ClosureIdRequest: {
            /** Format: int32 */
            id: number;
        };
        ClosureResponse: {
            /** Format: date */
            closure_date: string;
            /** Format: int32 */
            id: number;
            is_emergency?: boolean | null;
            /** Format: int32 */
            org_unit: number;
            reason: string;
        };
        ClosureRow: {
            /** Format: date */
            closure_date: string;
            /** Format: int32 */
            id: number;
            is_emergency: boolean;
            /** Format: int32 */
            org_unit: number;
            reason: string;
        };
        CreateAddressRequest: {
            address_line1?: string | null;
            address_line2?: string | null;
            address_type: string;
            city?: string | null;
            label: string;
            /** Format: int32 */
            org_unit: number;
            postal_code?: string | null;
            state_province?: string | null;
        };
        CreateClosureRequest: {
            /** Format: date */
            closure_date: string;
            is_emergency?: boolean | null;
            /** Format: int32 */
            org_unit: number;
            reason: string;
        };
        CreateOperatingHoursRequest: {
            close_time: string;
            /** Format: int32 */
            day_of_week: number;
            is_closed?: boolean | null;
            open_time: string;
            /** Format: int32 */
            org_unit: number;
        };
        CreateUnitRequest: {
            code: string;
            label: string;
            /**
             * Format: int32
             * @description Required: new units always attach below an existing unit.
             */
            parent: number;
            timezone?: string | null;
            /** Format: int32 */
            unit_type: number;
        };
        CreateUnitTypeRequest: {
            can_have_patrons?: boolean | null;
            can_have_staff?: boolean | null;
            label: string;
            /** Format: int32 */
            parent?: number | null;
        };
        LabelBatchRequest: {
            /** @description Lookup by database id. */
            ids?: number[];
            /**
             * @description Opt in to also resolve soft-deleted units (flagged with deleted_at).
             *     Default false keeps this active-only, so write-time existence checks
             *     still reject deleted ids.
             */
            include_deleted?: boolean;
            /**
             * @description Lookup by stable uuid (durable references). May be mixed with `ids`;
             *     entries are deduplicated in the response.
             */
            uuids?: string[];
        };
        LabelBatchResponse: {
            labels: components["schemas"]["OrgUnitLabelEntry"][];
        };
        ListUnitTypesRequest: components["schemas"]["Page"] & components["schemas"]["Sort"] & {
            search?: string | null;
        };
        OperatingHoursIdRequest: {
            /** Format: int32 */
            id: number;
        };
        OperatingHoursResponse: {
            close_time: string;
            /** Format: int32 */
            day_of_week: number;
            /** Format: int32 */
            id: number;
            is_closed?: boolean | null;
            open_time: string;
            /** Format: int32 */
            org_unit: number;
        };
        OperatingHoursRow: {
            close_time: string;
            /** Format: int32 */
            day_of_week: number;
            /** Format: int32 */
            id: number;
            is_closed: boolean;
            open_time: string;
            /** Format: int32 */
            org_unit: number;
        };
        OrgAdminSuccessResponse: {
            success: boolean;
        };
        OrgChildSuccessResponse: {
            success: boolean;
        };
        OrgUnitChildrenRequest: {
            /** Format: int32 */
            org_unit: number;
        };
        OrgUnitChildrenResponse: {
            addresses: components["schemas"]["AddressRow"][];
            closures: components["schemas"]["ClosureRow"][];
            operating_hours: components["schemas"]["OperatingHoursRow"][];
        };
        OrgUnitDetailResponse: {
            addresses: components["schemas"]["AddressResponse"][];
            future_closures: components["schemas"]["ClosureResponse"][];
            operating_hours: components["schemas"]["OperatingHoursResponse"][];
            org_unit: components["schemas"]["OrgUnitResponse"];
        };
        OrgUnitLabelEntry: {
            code: string;
            /** @description RFC3339 soft-delete timestamp; null for active units. */
            deleted_at?: string | null;
            /** Format: int32 */
            id: number;
            label: string;
            uuid: string;
        };
        OrgUnitResponse: {
            children?: components["schemas"]["OrgUnitResponse"][] | null;
            code: string;
            /**
             * @description RFC3339 soft-delete timestamp; null for active units. Only ever set on
             *     resolve-by-id responses (GET unit/{id}) — tree/scoping stay active-only.
             */
            deleted_at?: string | null;
            /** Format: int32 */
            id: number;
            label: string;
            /** Format: int32 */
            parent?: number | null;
            timezone?: string | null;
            unit_type: components["schemas"]["OrgUnitType"];
            /** @description Stable, DB-independent identity (see odo-durable-references). */
            uuid: string;
        };
        OrgUnitType: {
            can_have_patrons: boolean;
            can_have_staff: boolean;
            /** Format: int32 */
            id: number;
            label: string;
            /** Format: int32 */
            parent?: number | null;
        };
        /**
         * @description Standard pagination inputs for admin list endpoints. Flatten this into a
         *     per-resource request struct alongside that resource's own filter fields:
         *
         *     ```ignore
         *     #[derive(Deserialize, ToSchema)]
         *     pub struct ListThingsRequest {
         *         #[serde(default)]
         *         search: Option<String>,
         *         #[serde(flatten)]
         *         page: Page,
         *     }
         *     ```
         */
        Page: {
            /** Format: int64 */
            limit?: number | null;
            /** Format: int64 */
            offset?: number | null;
        };
        /**
         * @description Standard sort inputs for admin list endpoints. Flatten this into a
         *     per-resource request struct alongside `Page`:
         *
         *     ```ignore
         *     #[derive(Deserialize, ToSchema)]
         *     pub struct ListThingsRequest {
         *         #[serde(default)]
         *         search: Option<String>,
         *         #[serde(flatten)]
         *         page: Page,
         *         #[serde(flatten)]
         *         sort: Sort,
         *     }
         *     ```
         *
         *     `sort_by` is a client-supplied string, so a handler must NEVER map it to a
         *     column directly — resolve it against an explicit allow-list with
         *     [`Sort::resolve`], which falls back to the handler's default for any
         *     unknown or absent key.
         */
        Sort: {
            /** @description Logical column key to sort by (must be one the handler allow-lists). */
            sort_by?: string | null;
            sort_dir?: null | components["schemas"]["SortDir"];
        };
        /**
         * @description Sort direction for a list endpoint.
         * @enum {string}
         */
        SortDir: "asc" | "desc";
        UnitIdRequest: {
            /** Format: int32 */
            id: number;
        };
        UnitRow: {
            code: string;
            /** Format: int32 */
            id: number;
            label: string;
            /** Format: int32 */
            parent?: number | null;
            timezone?: string | null;
            /** Format: int32 */
            unit_type: number;
            unit_type_label: string;
        };
        UnitTypeIdRequest: {
            /** Format: int32 */
            id: number;
        };
        /** @description One page of org unit types. */
        UnitTypePage: {
            /** @description The rows on this page. */
            rows: components["schemas"]["UnitTypeRow"][];
            /**
             * Format: int64
             * @description Total rows matching the filter, ignoring limit/offset.
             */
            total: number;
        };
        UnitTypeRow: {
            can_have_patrons: boolean;
            can_have_staff: boolean;
            /** Format: int32 */
            id: number;
            label: string;
            /** Format: int32 */
            parent?: number | null;
            parent_label?: string | null;
            /**
             * Format: int64
             * @description Active org units of this type.
             */
            unit_count: number;
        };
        UpdateAddressRequest: {
            address_line1?: string | null;
            address_line2?: string | null;
            address_type?: string | null;
            city?: string | null;
            /** Format: int32 */
            id: number;
            label?: string | null;
            postal_code?: string | null;
            state_province?: string | null;
        };
        UpdateClosureRequest: {
            /** Format: date */
            closure_date?: string | null;
            /** Format: int32 */
            id: number;
            is_emergency?: boolean | null;
            reason?: string | null;
        };
        UpdateOperatingHoursRequest: {
            close_time?: string | null;
            /** Format: int32 */
            day_of_week?: number | null;
            /** Format: int32 */
            id: number;
            is_closed?: boolean | null;
            open_time?: string | null;
        };
        UpdateUnitRequest: {
            code?: string | null;
            /** Format: int32 */
            id: number;
            label?: string | null;
            /** Format: int32 */
            parent?: number | null;
            /** @description Empty string clears the timezone. */
            timezone?: string | null;
            /** Format: int32 */
            unit_type?: number | null;
        };
        UpdateUnitTypeRequest: {
            can_have_patrons?: boolean | null;
            can_have_staff?: boolean | null;
            /** Format: int32 */
            id: number;
            label?: string | null;
            /** Format: int32 */
            parent?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_address: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAddressRequest"];
            };
        };
        responses: {
            /** @description Newly-created address */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressRow"];
                };
            };
        };
    };
    delete_address: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressIdRequest"];
            };
        };
        responses: {
            /** @description Address deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgChildSuccessResponse"];
                };
            };
        };
    };
    update_address: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAddressRequest"];
            };
        };
        responses: {
            /** @description Updated address */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressRow"];
                };
            };
        };
    };
    create_closure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClosureRequest"];
            };
        };
        responses: {
            /** @description Newly-created closure */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosureRow"];
                };
            };
        };
    };
    delete_closure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClosureIdRequest"];
            };
        };
        responses: {
            /** @description Closure deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgChildSuccessResponse"];
                };
            };
        };
    };
    update_closure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClosureRequest"];
            };
        };
        responses: {
            /** @description Updated closure */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosureRow"];
                };
            };
        };
    };
    create_operating_hours: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOperatingHoursRequest"];
            };
        };
        responses: {
            /** @description Newly-created operating hours row */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatingHoursRow"];
                };
            };
        };
    };
    delete_operating_hours: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatingHoursIdRequest"];
            };
        };
        responses: {
            /** @description Operating hours row deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgChildSuccessResponse"];
                };
            };
        };
    };
    update_operating_hours: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOperatingHoursRequest"];
            };
        };
        responses: {
            /** @description Updated operating hours row */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatingHoursRow"];
                };
            };
        };
    };
    list_unit_children: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgUnitChildrenRequest"];
            };
        };
        responses: {
            /** @description All addresses, closures, and operating hours for one org unit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgUnitChildrenResponse"];
                };
            };
        };
    };
    create_unit_type: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUnitTypeRequest"];
            };
        };
        responses: {
            /** @description Newly-created org unit type */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitTypeRow"];
                };
            };
        };
    };
    delete_unit_type: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnitTypeIdRequest"];
            };
        };
        responses: {
            /** @description Org unit type deactivated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgAdminSuccessResponse"];
                };
            };
        };
    };
    list_unit_types: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListUnitTypesRequest"];
            };
        };
        responses: {
            /** @description Active org unit types with usage counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitTypePage"];
                };
            };
        };
    };
    update_unit_type: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUnitTypeRequest"];
            };
        };
        responses: {
            /** @description Updated org unit type */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitTypeRow"];
                };
            };
        };
    };
    create_unit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUnitRequest"];
            };
        };
        responses: {
            /** @description Newly-created org unit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitRow"];
                };
            };
        };
    };
    delete_unit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnitIdRequest"];
            };
        };
        responses: {
            /** @description Org unit deactivated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgAdminSuccessResponse"];
                };
            };
        };
    };
    update_unit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUnitRequest"];
            };
        };
        responses: {
            /** @description Updated org unit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitRow"];
                };
            };
        };
    };
    org_unit_root: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The root org unit (flat, no children) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgUnitResponse"];
                };
            };
        };
    };
    org_unit_tree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full org unit tree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgUnitResponse"];
                };
            };
        };
    };
    org_unit_label_batch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelBatchRequest"];
            };
        };
        responses: {
            /** @description Labels for the requested org-unit ids */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelBatchResponse"];
                };
            };
        };
    };
    org_unit_detail_by_uuid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org unit uuid */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgUnitDetailResponse"];
                };
            };
        };
    };
    org_unit_ancestors_by_uuid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org unit uuid */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgUnitResponse"][];
                };
            };
        };
    };
    org_unit_descendants_by_uuid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org unit uuid */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgUnitResponse"][];
                };
            };
        };
    };
    org_unit_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org unit ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Org unit detail with addresses, hours, and closures */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgUnitDetailResponse"];
                };
            };
        };
    };
    org_unit_ancestors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org unit ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ancestor chain from root to target */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgUnitResponse"][];
                };
            };
        };
    };
    org_unit_descendants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org unit ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All descendants (flat list) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgUnitResponse"][];
                };
            };
        };
    };
}
