/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/odo/asset/directory/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_directory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/asset/directory/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_directory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/asset/directory/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["list_directories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/asset/files/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/asset/files/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["get_files"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/asset/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/asset/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateDirectoryRequest: {
            /**
             * @description Restrict the mapping to one upload category; omit for the
             *     entity_type's catch-all. Requires entity_type.
             */
            category?: string | null;
            description?: string | null;
            /**
             * @description Route uploads with this entity_type under `path`. Optional: omit
             *     for a pure path-protection row.
             */
            entity_type?: string | null;
            /** @description Path prefix (no leading/trailing slash), e.g. `current/patron`. */
            path: string;
            /** @description Permission code required to read files under this prefix. */
            read_perm: string;
            /** @description Permission code required to upload/delete files under this prefix. */
            write_perm: string;
        };
        DeleteDirectoryRequest: {
            path: string;
        };
        DeleteDirectoryResponse: {
            deleted: boolean;
        };
        DeleteFileRequest: {
            /**
             * Format: int32
             * @description Database id of the file; alternatively pass `uuid`.
             */
            id?: number | null;
            /** @description Stable uuid of the file (durable references). */
            uuid?: string | null;
        };
        DeleteFileResponse: {
            /**
             * @description True when the on-disk file was unlinked. False when the file was
             *     missing or couldn't be removed (the DB row is deleted either way).
             */
            file_removed: boolean;
            /** Format: int32 */
            id: number;
            success: boolean;
        };
        DirectoryRow: {
            /**
             * @description Exact upload category this mapping serves; absent = the
             *     entity_type's catch-all.
             */
            category?: string | null;
            description?: string | null;
            /**
             * @description Uploads with this entity_type route under `path` (absent = a pure
             *     path-protection row with no upload routing).
             */
            entity_type?: string | null;
            path: string;
            read_perm: string;
            write_perm: string;
        };
        FileMetadata: {
            /** @description RFC3339 soft-delete timestamp; null for active files. */
            deleted_at?: string | null;
            file_name: string;
            /** Format: int32 */
            file_size?: number | null;
            file_type?: string | null;
            /** Format: int32 */
            id: number;
            relative_path: string;
            storage_path: string;
            uploaded_at: string;
            /** Format: int32 */
            uploaded_by: number;
            /** @description Stable uuid of the uploader (durable references). */
            uploaded_by_uuid?: string | null;
            /** @description Stable, DB-independent identity (see odo-durable-references). */
            uuid: string;
        };
        GetFilesRequest: {
            /** @description Lookup by database id. */
            ids?: number[];
            /**
             * @description Opt in to also return soft-deleted files (flagged with deleted_at).
             *     Default false keeps this active-only, so write-time attachment
             *     validation still rejects deleted ids.
             */
            include_deleted?: boolean;
            /**
             * @description Lookup by stable uuid (durable references). May be mixed with `ids`;
             *     unparseable/unknown uuids are silently dropped like unknown ids.
             */
            uuids?: string[];
        };
        GetFilesResponse: {
            files: components["schemas"]["FileMetadata"][];
        };
        ListDirectoriesRequest: Record<string, never>;
        UploadResponse: {
            /**
             * @description Echo of the multipart `category` field ("photo" | "document" |
             *     "video"). The DB doesn't persist this — it's derived from the
             *     destination directory. UI consumers use it to filter rendered
             *     attachment lists by kind.
             */
            category: string;
            entity_id?: string | null;
            entity_type?: string | null;
            filename: string;
            /** Format: int32 */
            id: number;
            mime_type: string;
            original_name: string;
            relative_path: string;
            /** Format: int64 */
            size: number;
            uploaded_at: string;
            /** Format: int32 */
            uploaded_by: number;
            /** @description Stable, DB-independent identity (see odo-durable-references). */
            uuid: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_directory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDirectoryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryRow"];
                };
            };
        };
    };
    delete_directory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteDirectoryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteDirectoryResponse"];
                };
            };
        };
    };
    list_directories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListDirectoriesRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryRow"][];
                };
            };
        };
    };
    delete_file: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteFileRequest"];
            };
        };
        responses: {
            /** @description Soft-deletes the file_upload row and unlinks the on-disk file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteFileResponse"];
                };
            };
        };
    };
    get_files: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetFilesRequest"];
            };
        };
        responses: {
            /** @description File metadata for the requested ids (missing/deleted ids are silently omitted) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetFilesResponse"];
                };
            };
        };
    };
    retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relative file path */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File contents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
