/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/odo/notify/email-group/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_email_group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/email-group/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["get_email_group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/email-group/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["list_email_groups"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/email-group/member/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_email_group_member"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/email-group/member/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_email_group_member"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/email-group/member/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_email_group_member"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/email-group/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_email_group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/enqueue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enqueue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/inbox/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dismiss"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/inbox/dismiss-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dismiss_all"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/inbox/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/inbox/mark-all-read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mark_all_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/inbox/mark-read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mark_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/template/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_template"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/template/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_template"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/template/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["list_templates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/template/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["preview_template"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odo/notify/template/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_template"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateEmailGroupMemberRequest: {
            email: string;
            /** Format: int32 */
            email_group: number;
            is_active?: boolean | null;
        };
        CreateEmailGroupRequest: {
            code: string;
            is_active?: boolean | null;
            label: string;
        };
        CreateTemplateRequest: {
            body_template: string;
            body_template_html?: string | null;
            code: string;
            description?: string | null;
            is_active?: boolean | null;
            name: string;
            /**
             * Format: int32
             * @description Defaults to the root org unit.
             */
            org_unit?: number | null;
            sample_data?: unknown;
            subject_template: string;
        };
        DeliveryIdRequest: {
            /** Format: int64 */
            delivery_id: number;
        };
        DeliveryInfo: {
            channel: string;
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            recipient_email_group?: number | null;
            /** Format: int32 */
            recipient_user?: number | null;
            status: string;
        };
        EmailGroupDetailResponse: {
            group: components["schemas"]["EmailGroupRow"];
            members: components["schemas"]["EmailGroupMemberRow"][];
        };
        EmailGroupIdRequest: {
            /** Format: int32 */
            id: number;
        };
        EmailGroupMemberIdRequest: {
            /** Format: int32 */
            id: number;
        };
        EmailGroupMemberRow: {
            /** Format: date-time */
            created_at: string;
            email: string;
            /** Format: int32 */
            email_group: number;
            /** Format: int32 */
            id: number;
            is_active: boolean;
        };
        /** @description One page of email groups. */
        EmailGroupPage: {
            /** @description The rows on this page. */
            rows: components["schemas"]["EmailGroupRow"][];
            /**
             * Format: int64
             * @description Total rows matching the filter, ignoring limit/offset.
             */
            total: number;
        };
        EmailGroupRow: {
            /** Format: int64 */
            active_member_count: number;
            code: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            id: number;
            is_active: boolean;
            label: string;
            /** Format: int64 */
            member_count: number;
            /** Format: date-time */
            updated_at: string;
        };
        EnqueueRequest: {
            dedup_key?: string | null;
            recipients: components["schemas"]["Recipient"][];
            scheduled_for?: string | null;
            /** Format: int64 */
            source_entity_id?: number | null;
            source_entity_type?: string | null;
            source_service?: string | null;
            template_code: string;
            template_variables?: unknown;
        };
        EnqueueResponse: {
            deliveries: components["schemas"]["DeliveryInfo"][];
            /** Format: int64 */
            event_id: number;
            is_duplicate: boolean;
        };
        ListEmailGroupsRequest: components["schemas"]["Page"] & components["schemas"]["Sort"] & {
            include_inactive?: boolean;
            search?: string | null;
        };
        ListRequest: {
            /** Format: int64 */
            limit?: number;
            /** Format: int64 */
            offset?: number;
        };
        ListResponse: {
            notifications: components["schemas"]["NotificationItem"][];
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            unread_count: number;
        };
        ListTemplatesRequest: components["schemas"]["Page"] & components["schemas"]["Sort"] & {
            search?: string | null;
        };
        NotificationItem: {
            action_url?: string | null;
            body?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            delivery_id: number;
            /** Format: int64 */
            event_id: number;
            is_read: boolean;
            /** Format: int64 */
            source_entity_id?: number | null;
            source_entity_type?: string | null;
            source_service?: string | null;
            template_code?: string | null;
            title: string;
        };
        /**
         * @description Standard pagination inputs for admin list endpoints. Flatten this into a
         *     per-resource request struct alongside that resource's own filter fields:
         *
         *     ```ignore
         *     #[derive(Deserialize, ToSchema)]
         *     pub struct ListThingsRequest {
         *         #[serde(default)]
         *         search: Option<String>,
         *         #[serde(flatten)]
         *         page: Page,
         *     }
         *     ```
         */
        Page: {
            /** Format: int64 */
            limit?: number | null;
            /** Format: int64 */
            offset?: number | null;
        };
        PreviewRequest: {
            body_template?: string | null;
            body_template_html?: string | null;
            subject_template?: string | null;
            variables?: unknown;
        };
        PreviewResponse: {
            body?: string | null;
            body_html?: string | null;
            subject?: string | null;
        };
        Recipient: {
            channels: string[];
            /** @enum {string} */
            type: "user";
            /** Format: int64 */
            user_id: number;
        } | {
            channels: string[];
            /** Format: int64 */
            email_group_id: number;
            /** @enum {string} */
            type: "email_group";
        };
        /**
         * @description Standard sort inputs for admin list endpoints. Flatten this into a
         *     per-resource request struct alongside `Page`:
         *
         *     ```ignore
         *     #[derive(Deserialize, ToSchema)]
         *     pub struct ListThingsRequest {
         *         #[serde(default)]
         *         search: Option<String>,
         *         #[serde(flatten)]
         *         page: Page,
         *         #[serde(flatten)]
         *         sort: Sort,
         *     }
         *     ```
         *
         *     `sort_by` is a client-supplied string, so a handler must NEVER map it to a
         *     column directly — resolve it against an explicit allow-list with
         *     [`Sort::resolve`], which falls back to the handler's default for any
         *     unknown or absent key.
         */
        Sort: {
            /** @description Logical column key to sort by (must be one the handler allow-lists). */
            sort_by?: string | null;
            sort_dir?: null | components["schemas"]["SortDir"];
        };
        /**
         * @description Sort direction for a list endpoint.
         * @enum {string}
         */
        SortDir: "asc" | "desc";
        SuccessResponse: {
            success: boolean;
        };
        TemplateIdRequest: {
            /** Format: int32 */
            id: number;
        };
        /** @description One page of email templates. */
        TemplatePage: {
            /** @description The rows on this page. */
            rows: components["schemas"]["TemplateRow"][];
            /**
             * Format: int64
             * @description Total rows matching the filter, ignoring limit/offset.
             */
            total: number;
        };
        TemplateRow: {
            body_template: string;
            body_template_html?: string | null;
            code: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            created_by: number;
            description?: string | null;
            /** Format: int32 */
            id: number;
            is_active: boolean;
            name: string;
            /** Format: int32 */
            org_unit: number;
            sample_data?: unknown;
            subject_template: string;
            /** Format: date-time */
            updated_at: string;
        };
        UpdateEmailGroupMemberRequest: {
            email?: string | null;
            /** Format: int32 */
            id: number;
            is_active?: boolean | null;
        };
        UpdateEmailGroupRequest: {
            code?: string | null;
            /** Format: int32 */
            id: number;
            is_active?: boolean | null;
            label?: string | null;
        };
        UpdateTemplateRequest: {
            body_template?: string | null;
            /** @description Empty string clears the HTML variant. */
            body_template_html?: string | null;
            code?: string | null;
            description?: string | null;
            /** Format: int32 */
            id: number;
            is_active?: boolean | null;
            name?: string | null;
            sample_data?: unknown;
            subject_template?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_email_group: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmailGroupRequest"];
            };
        };
        responses: {
            /** @description Newly-created email group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailGroupRow"];
                };
            };
        };
    };
    get_email_group: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailGroupIdRequest"];
            };
        };
        responses: {
            /** @description Email group with its members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailGroupDetailResponse"];
                };
            };
        };
    };
    list_email_groups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListEmailGroupsRequest"];
            };
        };
        responses: {
            /** @description Email groups with member counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailGroupPage"];
                };
            };
        };
    };
    create_email_group_member: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmailGroupMemberRequest"];
            };
        };
        responses: {
            /** @description Newly-added email group member */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailGroupMemberRow"];
                };
            };
        };
    };
    delete_email_group_member: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailGroupMemberIdRequest"];
            };
        };
        responses: {
            /** @description Email group member deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    update_email_group_member: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmailGroupMemberRequest"];
            };
        };
        responses: {
            /** @description Updated email group member */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailGroupMemberRow"];
                };
            };
        };
    };
    update_email_group: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmailGroupRequest"];
            };
        };
        responses: {
            /** @description Updated email group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailGroupRow"];
                };
            };
        };
    };
    enqueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnqueueRequest"];
            };
        };
        responses: {
            /** @description Notification enqueued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueueResponse"];
                };
            };
        };
    };
    dismiss: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryIdRequest"];
            };
        };
        responses: {
            /** @description Notification dismissed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    dismiss_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All notifications dismissed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListRequest"];
            };
        };
        responses: {
            /** @description User's in-app notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
        };
    };
    mark_all_read: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All notifications marked as read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    mark_read: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryIdRequest"];
            };
        };
        responses: {
            /** @description Notification marked as read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    create_template: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateRequest"];
            };
        };
        responses: {
            /** @description Newly-created template */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateRow"];
                };
            };
        };
    };
    delete_template: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateIdRequest"];
            };
        };
        responses: {
            /** @description Template soft-deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    list_templates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListTemplatesRequest"];
            };
        };
        responses: {
            /** @description Notification templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplatePage"];
                };
            };
        };
    };
    preview_template: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewRequest"];
            };
        };
        responses: {
            /** @description Rendered template preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
        };
    };
    update_template: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTemplateRequest"];
            };
        };
        responses: {
            /** @description Updated template */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateRow"];
                };
            };
        };
    };
}
