apiVersion: v1
kind: Service
metadata:
  name: odo-org
  namespace: odo-pub
  labels:
    app: odo-org
    part-of: odo
spec:
  type: NodePort
  selector:
    app: odo-org
  ports:
  - name: http
    port: 8080
    targetPort: http
    nodePort: 30040
    protocol: TCP
