//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "org", table_name = "closure")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub org_unit: i32,
    pub closure_date: Date,
    pub reason: String,
    pub is_emergency: Option<bool>,
    pub created_by: Option<i32>,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::unit::Entity",
        from = "Column::OrgUnit",
        to = "super::unit::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Unit,
}

impl Related<super::unit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Unit.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
