//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::address::Entity as Address;
pub use super::closure::Entity as Closure;
pub use super::operating_hours::Entity as OperatingHours;
pub use super::unit::Entity as Unit;
pub use super::unit_type::Entity as UnitType;
