//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "org", table_name = "unit")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub label: String,
    #[sea_orm(column_type = "Text", unique)]
    pub code: String,
    pub parent: Option<i32>,
    pub unit_type: i32,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub timezone: Option<String>,
    #[sea_orm(unique)]
    pub uuid: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::address::Entity")]
    Address,
    #[sea_orm(has_many = "super::closure::Entity")]
    Closure,
    #[sea_orm(has_many = "super::operating_hours::Entity")]
    OperatingHours,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::Parent",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(
        belongs_to = "super::unit_type::Entity",
        from = "Column::UnitType",
        to = "super::unit_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UnitType,
}

impl Related<super::address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Address.def()
    }
}

impl Related<super::closure::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Closure.def()
    }
}

impl Related<super::operating_hours::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OperatingHours.def()
    }
}

impl Related<super::unit_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UnitType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
