apiVersion: v1
kind: Service
metadata:
  name: odo-auth
  namespace: odo-pub
  labels:
    app: odo-auth
    part-of: odo
spec:
  type: NodePort
  selector:
    app: odo-auth
  ports:
  - name: http
    port: 8080
    targetPort: http
    nodePort: 30042
    protocol: TCP
