//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::permission::Entity as Permission;
pub use super::role::Entity as Role;
pub use super::role_permission::Entity as RolePermission;
pub use super::saml_attr_role_map::Entity as SamlAttrRoleMap;
pub use super::usr_role_org_map::Entity as UsrRoleOrgMap;
