//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "authz", table_name = "role")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub code: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub label: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::role_permission::Entity")]
    RolePermission,
    #[sea_orm(has_many = "super::saml_attr_role_map::Entity")]
    SamlAttrRoleMap,
    #[sea_orm(has_many = "super::usr_role_org_map::Entity")]
    UsrRoleOrgMap,
}

impl Related<super::role_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RolePermission.def()
    }
}

impl Related<super::saml_attr_role_map::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlAttrRoleMap.def()
    }
}

impl Related<super::usr_role_org_map::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsrRoleOrgMap.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
