//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "authz", table_name = "saml_attr_role_map")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub is_active: bool,
    #[sea_orm(unique_key = "uniq_role_per_attr_value")]
    pub attr: i32,
    #[sea_orm(column_type = "Text", unique_key = "uniq_role_per_attr_value")]
    pub role: String,
    #[sea_orm(column_type = "Text", unique_key = "uniq_role_per_attr_value")]
    pub attr_value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::role::Entity",
        from = "Column::Role",
        to = "super::role::Column::Code",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Role,
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Role.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
