apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: odo-core
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 32345
    protocol: TCP
    name: postgres
  selector:
    app: postgres
