//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "asset", table_name = "directory")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[sea_orm(column_type = "Text")]
    pub path: String,
    #[sea_orm(column_type = "Text")]
    pub read_perm: String,
    #[sea_orm(column_type = "Text")]
    pub write_perm: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    /// Uploads with this entity_type route under `path` (NULL = a pure
    /// path-protection row with no upload routing).
    #[sea_orm(column_type = "Text", nullable)]
    pub entity_type: Option<String>,
    /// Exact upload category this mapping serves; NULL is the
    /// entity_type's catch-all.
    #[sea_orm(column_type = "Text", nullable)]
    pub category: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
