apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - odo-routes.yaml
  - odo-admin-routes.yaml
  - odo-security.yaml
  - saml-legacy-routes.yaml
  - asset-migration-routes.yaml
