-- Revert odo:001_odo_baseline from pg

BEGIN;

DROP SCHEMA IF EXISTS asset CASCADE;
DROP SCHEMA IF EXISTS auth CASCADE;
DROP SCHEMA IF EXISTS authz CASCADE;
DROP SCHEMA IF EXISTS notification CASCADE;
DROP SCHEMA IF EXISTS org CASCADE;
DROP SCHEMA IF EXISTS audit CASCADE;

COMMIT;
