//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "notification", table_name = "delivery")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "uq_delivery_event_channel_email_group")]
    pub event_id: i64,
    #[sea_orm(unique_key = "uq_delivery_event_channel_email_group")]
    pub channel: String,
    pub template_code: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub title_rendered: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub body_rendered: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub action_url: Option<String>,
    pub status: String,
    pub scheduled_for: Option<DateTimeWithTimeZone>,
    pub processing_started_at: Option<DateTimeWithTimeZone>,
    pub processing_expires_at: Option<DateTimeWithTimeZone>,
    pub processing_owner: Option<String>,
    pub processed_at: Option<DateTimeWithTimeZone>,
    pub retry_count: i32,
    pub max_retries: i32,
    pub next_retry_at: Option<DateTimeWithTimeZone>,
    pub error_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub channel_metadata: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(unique_key = "uq_delivery_event_channel_user")]
    pub recipient_user: Option<i32>,
    #[sea_orm(unique_key = "uq_delivery_event_channel_email_group")]
    pub recipient_email_group: Option<i32>,
    pub read_at: Option<DateTimeWithTimeZone>,
    pub dismissed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::email_group::Entity",
        from = "Column::RecipientEmailGroup",
        to = "super::email_group::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EmailGroup,
    #[sea_orm(
        belongs_to = "super::event::Entity",
        from = "Column::EventId",
        to = "super::event::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Event,
}

impl Related<super::email_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmailGroup.def()
    }
}

impl Related<super::event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Event.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
