//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "notification", table_name = "email_group_member")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "uq_email_group_member")]
    pub email_group: i32,
    #[sea_orm(unique_key = "uq_email_group_member")]
    pub email: String,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::email_group::Entity",
        from = "Column::EmailGroup",
        to = "super::email_group::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EmailGroup,
}

impl Related<super::email_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmailGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
