//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "notification", table_name = "event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub dedup_key: Option<String>,
    pub template_code: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub template_variables: Json,
    pub source_service: Option<String>,
    pub source_entity_type: Option<String>,
    pub source_entity_id: Option<i64>,
    pub created_by: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::delivery::Entity")]
    Delivery,
}

impl Related<super::delivery::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Delivery.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
