//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "auth", table_name = "audit_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub action: String,
    pub resource_type: Option<String>,
    pub resource_id: Option<String>,
    #[sea_orm(ignore, column_type = "custom(\"inet\")", select_as = "text", nullable)]
    pub ip_address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub details: Option<Json>,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::usr::Entity",
        from = "Column::UserId",
        to = "super::usr::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Usr,
}

impl Related<super::usr::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usr.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
