//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "auth", table_name = "local_account")]
pub struct Model {
    pub usr: i32,
    pub failed_login_attempts: Option<i32>,
    pub locked_until: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub password_hash: String,
    #[sea_orm(primary_key)]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::usr::Entity",
        from = "Column::Usr",
        to = "super::usr::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Usr,
}

impl Related<super::usr::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usr.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
