//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod audit_log;
pub mod local_account;
pub mod saml_auth_requests;
pub mod saml_idp_attribute;
pub mod saml_idp_config;
pub mod saml_session;
pub mod saml_sp_config;
pub mod saml_usr_attr;
pub mod saml_usr_working_location;
pub mod session;
pub mod usr;
pub mod usr_saml_identities;
