//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::audit_log::Entity as AuditLog;
pub use super::local_account::Entity as LocalAccount;
pub use super::saml_auth_requests::Entity as SamlAuthRequests;
pub use super::saml_idp_attribute::Entity as SamlIdpAttribute;
pub use super::saml_idp_config::Entity as SamlIdpConfig;
pub use super::saml_session::Entity as SamlSession;
pub use super::saml_sp_config::Entity as SamlSpConfig;
pub use super::saml_usr_attr::Entity as SamlUsrAttr;
pub use super::saml_usr_working_location::Entity as SamlUsrWorkingLocation;
pub use super::session::Entity as Session;
pub use super::usr::Entity as Usr;
pub use super::usr_saml_identities::Entity as UsrSamlIdentities;
