//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "auth", table_name = "saml_session")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub session_index: String,
    pub idp_id: i32,
    pub name_id: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub session_data: Option<Json>,
    pub session: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::saml_idp_config::Entity",
        from = "Column::IdpId",
        to = "super::saml_idp_config::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SamlIdpConfig,
    #[sea_orm(
        belongs_to = "super::session::Entity",
        from = "Column::Session",
        to = "super::session::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Session,
}

impl Related<super::saml_idp_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlIdpConfig.def()
    }
}

impl Related<super::session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Session.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
