//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "auth", table_name = "saml_idp_attribute")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "uniq_attr_per_idp")]
    pub idp: i32,
    #[sea_orm(unique_key = "uniq_attr_per_idp")]
    pub key: String,
    pub label: String,
    pub is_location: bool,
    #[sea_orm(unique_key = "uniq_attr_per_idp")]
    pub normalizer: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::saml_idp_config::Entity",
        from = "Column::Idp",
        to = "super::saml_idp_config::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SamlIdpConfig,
    #[sea_orm(has_many = "super::saml_usr_attr::Entity")]
    SamlUsrAttr,
}

impl Related<super::saml_idp_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlIdpConfig.def()
    }
}

impl Related<super::saml_usr_attr::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlUsrAttr.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
