//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "auth", table_name = "saml_idp_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub entity_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub sso_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub slo_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata_url: Option<String>,
    pub is_active: Option<bool>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub attribute_mapping: Option<Json>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub name: String,
    pub session_lifetime_hours: Option<i32>,
    pub allow_idp_initiated: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::saml_auth_requests::Entity")]
    SamlAuthRequests,
    #[sea_orm(has_many = "super::saml_idp_attribute::Entity")]
    SamlIdpAttribute,
    #[sea_orm(has_many = "super::saml_session::Entity")]
    SamlSession,
    #[sea_orm(has_many = "super::saml_sp_config::Entity")]
    SamlSpConfig,
    #[sea_orm(has_many = "super::usr_saml_identities::Entity")]
    UsrSamlIdentities,
}

impl Related<super::saml_auth_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlAuthRequests.def()
    }
}

impl Related<super::saml_idp_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlIdpAttribute.def()
    }
}

impl Related<super::saml_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlSession.def()
    }
}

impl Related<super::saml_sp_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlSpConfig.def()
    }
}

impl Related<super::usr_saml_identities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsrSamlIdentities.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
