//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "auth", table_name = "saml_usr_attr")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "uniq_attr_per_ident")]
    pub ident: i32,
    #[sea_orm(unique_key = "uniq_attr_per_ident")]
    pub attr: i32,
    #[sea_orm(column_type = "Text")]
    pub value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::saml_idp_attribute::Entity",
        from = "Column::Attr",
        to = "super::saml_idp_attribute::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SamlIdpAttribute,
    #[sea_orm(
        belongs_to = "super::usr_saml_identities::Entity",
        from = "Column::Ident",
        to = "super::usr_saml_identities::Column::UserId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UsrSamlIdentities,
}

impl Related<super::saml_idp_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlIdpAttribute.def()
    }
}

impl Related<super::usr_saml_identities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsrSamlIdentities.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
