//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "auth", table_name = "saml_auth_requests")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub request_id: String,
    pub idp_id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub relay_state: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub request_data: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub acs_url: Option<String>,
    pub sp_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::saml_idp_config::Entity",
        from = "Column::IdpId",
        to = "super::saml_idp_config::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SamlIdpConfig,
    #[sea_orm(
        belongs_to = "super::saml_sp_config::Entity",
        from = "Column::SpId",
        to = "super::saml_sp_config::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SamlSpConfig,
}

impl Related<super::saml_idp_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlIdpConfig.def()
    }
}

impl Related<super::saml_sp_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlSpConfig.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
