//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "auth", table_name = "saml_sp_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub entity_id: String,
    #[sea_orm(column_type = "Text")]
    pub acs_url: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub slo_url: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub x509_cert: String,
    #[sea_orm(column_type = "Text")]
    pub private_key: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata_url: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub callback_url: Option<String>,
    pub is_active: bool,
    pub idp: Option<i32>,
    pub label: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub idp_x509_cert: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::saml_auth_requests::Entity")]
    SamlAuthRequests,
    #[sea_orm(
        belongs_to = "super::saml_idp_config::Entity",
        from = "Column::Idp",
        to = "super::saml_idp_config::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SamlIdpConfig,
}

impl Related<super::saml_auth_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlAuthRequests.def()
    }
}

impl Related<super::saml_idp_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlIdpConfig.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
