//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "auth", table_name = "session")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub usr: i32,
    #[sea_orm(unique)]
    pub token_hash: String,
    #[sea_orm(unique)]
    pub refresh_token_hash: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub auth_method: String,
    #[sea_orm(ignore, column_type = "custom(\"inet\")", select_as = "text", nullable)]
    pub ip_address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent: Option<String>,
    pub is_active: Option<bool>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub expires_at: DateTimeWithTimeZone,
    pub last_activity_at: Option<DateTimeWithTimeZone>,
    pub org_unit: Option<i32>,
    #[sea_orm(unique)]
    pub uuid: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::saml_session::Entity")]
    SamlSession,
    #[sea_orm(
        belongs_to = "super::usr::Entity",
        from = "Column::Usr",
        to = "super::usr::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Usr,
}

impl Related<super::saml_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlSession.def()
    }
}

impl Related<super::usr::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usr.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
