//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "auth", table_name = "usr")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(unique)]
    pub username: Option<String>,
    pub first_given_name: Option<String>,
    pub second_given_name: Option<String>,
    pub family_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub status: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub auth_method: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub last_login_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub deleted_by: Option<i32>,
    #[sea_orm(unique)]
    pub uuid: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::audit_log::Entity")]
    AuditLog,
    #[sea_orm(has_many = "super::local_account::Entity")]
    LocalAccount,
    #[sea_orm(has_many = "super::session::Entity")]
    Session,
    #[sea_orm(has_one = "super::usr_saml_identities::Entity")]
    UsrSamlIdentities,
}

impl Related<super::audit_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditLog.def()
    }
}

impl Related<super::local_account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LocalAccount.def()
    }
}

impl Related<super::session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Session.def()
    }
}

impl Related<super::usr_saml_identities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsrSamlIdentities.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
