//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "auth", table_name = "usr_saml_identities")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i32,
    #[sea_orm(unique_key = "saml_account_idp_id_subject_id_key")]
    pub idp_id: i32,
    #[sea_orm(unique_key = "saml_account_idp_id_subject_id_key")]
    pub name_id: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub attributes: Option<Json>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub name_id_format: Option<String>,
    pub session_index: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::saml_idp_config::Entity",
        from = "Column::IdpId",
        to = "super::saml_idp_config::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SamlIdpConfig,
    #[sea_orm(has_many = "super::saml_usr_attr::Entity")]
    SamlUsrAttr,
    #[sea_orm(has_many = "super::saml_usr_working_location::Entity")]
    SamlUsrWorkingLocation,
    #[sea_orm(
        belongs_to = "super::usr::Entity",
        from = "Column::UserId",
        to = "super::usr::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Usr,
}

impl Related<super::saml_idp_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlIdpConfig.def()
    }
}

impl Related<super::saml_usr_attr::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlUsrAttr.def()
    }
}

impl Related<super::saml_usr_working_location::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlUsrWorkingLocation.def()
    }
}

impl Related<super::usr::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usr.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
