[package]
name = "odo-org"
version = "0.1.0"
edition = "2024"

[dependencies]
odo-client = { path = "../odo-client" }
odo-service = { path = "../odo-service" }
odo-entity = { path = "../odo-entity" }

sea-orm = { version = "2.0", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "with-chrono",
    "with-json",
    "with-uuid",
    "debug-print",
] }

axum = "0.8"
utoipa = { version = "5", features = ["axum_extras", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
log = { version = "0.4", features = ["kv_serde"] }
tokio = { version = "1.35", features = ["full"] }
tower-http = { version = "0.5", features = ["cors", "trace"] }
tracing = "0.1"

[[bin]]
name = "odo-org"
path = "src/bin/odo-org.rs"
